apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
  namespace: prod
spec:
  selector:
    matchLabels:
      app: productcatalogservice
  template:
    metadata:
      labels:
        app: productcatalogservice
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: gmj06/productcatalogservice:latest
        ports:
        - containerPort: 3551
        env:
        - name: PORT
          value: "3551"
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:3551"]
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:3551"]
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
spec:
  type: ClusterIP
  selector:
    app: productcatalogservice
  ports:
  - name: grpc
    port: 3551
    targetPort: 3551
