apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: udacityshop-dev
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes-manifests/dev
    repoURL: https://github.com/gmj06/UdaCityShop.git
    targetRevision: HEAD
  syncPolicy: 
    automated: 
      prune: true
      selfHeal: true