##  Named of the workflow.
name: Uda'CityShop [sha tag] - Package with Docker

## Set the trigger policy.
## In this case, the workflow is execute on a `push` event,
## or when a new commit is pushed to the repository
on:
  push:
    branches: [main]

## List the steps to be executed by the workflow
jobs:
  ## Set the name of the job
  docker:
    ## Configure the operating system the workflow should run on.
    ## In this case, the job on Ubuntu
    runs-on: ubuntu-latest
    
    ## Define a sequence of steps to be executed
    steps:
      ## Use the public `checkout` actoin  in version v2
      ## to checkout the existing code in the repository
      - name: Checkout
        uses: actions/checkout@v2
     
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta-frontend
        uses: docker/metadata-action@v3
        with:
          images: gmj06/frontend
          tags: type=sha
      
      - name: Build and push frontend image
        uses: docker/build-push-action@v2
        with:
          context: src/frontend/
          file: src/frontend/Dockerfile
          push: true
          tags: ${{ steps.meta-frontend.outputs.tags }}
          
      
      - name: Docker meta
        id: meta-productcatalogservice
        uses: docker/metadata-action@v3
        with:
          images: gmj06/productcatalogservice
          tags: type=sha

      - name: Build and push productcatalogservice image
        uses: docker/build-push-action@v2
        with:
          context: src/productcatalogservice/
          file: src/productcatalogservice/Dockerfile
          push: true
          tags: ${{ steps.meta-productcatalogservice.outputs.tags }}
          

      - name: Docker meta
        id: meta-adservice
        uses: docker/metadata-action@v3
        with:
          images: gmj06/adservice
          tags: type=sha

      - name: Build and push adservice image
        uses: docker/build-push-action@v2
        with:
          context: src/adservice/
          file: src/adservice/Dockerfile
          push: true
          tags: ${{ steps.meta-adservice.outputs.tags }}

      - name: Docker meta
        id: meta-adservicev2
        uses: docker/metadata-action@v3
        with:
          images: gmj06/adservice-v2
          tags: type=sha

      - name: Build and push adservicev2 image
        uses: docker/build-push-action@v2
        with:
          context: src/adservice-v2/
          file: src/adservice-v2/Dockerfile
          push: true
          tags: ${{ steps.meta-adservicev2.outputs.tags }}
         
      - name: Docker meta
        id: meta-currencyservice
        uses: docker/metadata-action@v3
        with:
          images: gmj06/currencyservice
          tags: type=sha


      - name: Build and push currencyservice image
        uses: docker/build-push-action@v2
        with:
          context: src/currencyservice/
          file: src/currencyservice/Dockerfile
          push: true
          tags: ${{ steps.meta-currencyservice.outputs.tags }}
         